# Generated by Django 3.0 on 2019-12-10 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.CharField(choices=[('admin', '管理员'), ('student', '学生'), ('teacher', '老师')], default='学生', max_length=32)),
                ('access_to_assign', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaperBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaperHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Qsystem.Authority')),
            ],
        ),
        migrations.CreateModel(
            name='UserPaperDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date finished')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qsystem.PaperHead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qsystem.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date answered')),
                ('inPaper', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qsystem.UserPaperDetail')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qsystem.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qsystem.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='complete',
            field=models.ManyToManyField(through='Qsystem.UserQuestionDetail', to='Qsystem.Question'),
        ),
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=256)),
                ('likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qsystem.User')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Qsystem.User'),
        ),
        migrations.AddField(
            model_name='paperhead',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Qsystem.User'),
        ),
        migrations.AddField(
            model_name='paperhead',
            name='question',
            field=models.ManyToManyField(through='Qsystem.PaperBody', to='Qsystem.Question'),
        ),
        migrations.CreateModel(
            name='PaperComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=256)),
                ('likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qsystem.User')),
                ('paper_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qsystem.PaperHead')),
            ],
        ),
        migrations.AddField(
            model_name='paperbody',
            name='paper_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qsystem.PaperHead'),
        ),
        migrations.AddField(
            model_name='paperbody',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qsystem.Question'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=256)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Qsystem.Area')),
            ],
        ),
    ]
