# Generated by Django 3.0 on 2020-04-06 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.CharField(choices=[('admin', '管理员'), ('student', '学生'), ('teacher', '老师')], default='学生', max_length=32)),
                ('access_to_assign', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_Id', models.CharField(default='N/A', max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('phone', models.CharField(default='N/A', max_length=128)),
                ('money', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('1', '取款'), ('2', '存款'), ('3', '结余')], default='取款', max_length=32)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('left', models.DecimalField(decimal_places=4, max_digits=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qsystem.User')),
            ],
        ),
    ]
