# Generated by Django 3.0 on 2019-12-12 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qsystem', '0002_auto_20191211_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncomment',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Qsystem.Question'),
        ),
    ]
