# Generated by Django 3.0 on 2019-12-12 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qsystem', '0004_auto_20191212_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='isTrue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Qsystem.Question'),
        ),
        migrations.AddField(
            model_name='userquestiondetail',
            name='option',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qsystem.Option'),
        ),
    ]
