# Generated by Django 3.0 on 2019-12-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qsystem', '0005_auto_20191212_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='area',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='A_text',
            field=models.CharField(default='请输入选项', max_length=256),
        ),
        migrations.AddField(
            model_name='question',
            name='B_text',
            field=models.CharField(default='请输入选项', max_length=256),
        ),
        migrations.AddField(
            model_name='question',
            name='C_text',
            field=models.CharField(default='请输入选项', max_length=256),
        ),
        migrations.AddField(
            model_name='question',
            name='D_text',
            field=models.CharField(default='请输入选项', max_length=256),
        ),
        migrations.AlterField(
            model_name='userquestiondetail',
            name='option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='男', max_length=32),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
