# Generated by Django 3.0 on 2019-12-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qsystem', '0008_auto_20191213_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestiondetail',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
    ]
