# Generated by Django 3.0 on 2019-12-13 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qsystem', '0009_userquestiondetail_is_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpQuestionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date finished')),
                ('question_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qsystem.QuestionComment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Qsystem.User')),
            ],
        ),
    ]
